from setuptools import setup, find_packages

setup(
    name="mnist-deep-learning-classification",
    version="1.0.0",
    description="Industry-grade handwritten digit recognition with deep learning",
    author="Your Name",
    author_email="your.email@domain.com",
    packages=find_packages(),
    install_requires=[
        "opencv-python-headless==4.5.3.56",
        "matplotlib==3.4.3",
        "numpy==1.21.2",
        "pillow==7.0.0",
        "bokeh==2.1.1",
        "torch==1.11.0",
        "torchvision==0.12.0",
        "tqdm==4.63.0",
        "ipywidgets==7.7.0",
        "livelossplot==0.5.4",
        "pytest==7.1.1",
        "pandas==1.3.5",
        "seaborn==0.11.2",
        "jupyter==1.0.0",
        "ipykernel==4.10.0",
        "argparse>=1.4.0",
        "scikit-learn>=1.0.0",
        "seaborn>=0.11.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)